### ISSUE TITLE
Motif view: sorting anitbody name

### ISSUE THREAD

**Issue by Raziel01** [TravisCG/summitwebsite#20] opened 2018-12-11 13:46 UTC
In motif view, under "Plot options", the "Alphabetical by name" button doesn't work properly.

**Comment by TravisCG** [comment] 2018-12-12 08:28
Looks like non of them worked. The bug is fixed.

**Comment by Raziel01** [comment] 2018-12-14 13:28
The buttons still not working on Firefox. On chrome they are working.

**Comment by TravisCG** [comment] 2018-12-15 11:26
I cannot reproduce the bug (I am using Firefox for developing the site). Have you tried to refresh your browser? If it is still not working, please add more detail: type of the motif, operating system, Firefox version.

**Comment by TravisCG** [comment] 2019-01-15 08:15
Because there is no further info, I will close this.

**Closed as completed by TravisCG** 2019-01-15 08:15 UTC
