### ISSUE TITLE
Experiment view

### ISSUE THREAD

**Issue by Raziel01** [TravisCG/summitwebsite#24] opened 2019-01-15 09:44 UTC
Hi,

It just an opinion. I think "SRX search" should be opened in a new tab. 

Is it possible, that the experiment view record contain a list and links to the Motif views? I'm thinkng about the involved motifs, which overlap with the selected experiment.

**Comment by TravisCG** [comment] 2019-01-15 10:33
You mean if the user click a specific experiment in the Experiment Preview, the details of the selected experiment should be seen in a new tab?

For the second question: yes, it is possible.

**Comment by TravisCG** [comment] 2019-01-15 11:27
The first one implemented. The second one is also done, but the link contains default values about the overlap, standard deviation, etc, so it is possible to miss the initial experiment.

**Comment by Raziel01** [comment] 2019-01-15 11:58
Splendid! The list is exactly how I meant. Now I'm checking the result and the following came to my mind: It would be helpful, if the number of motif- summit overlap would be shown (next to the motif name). Maybe the list should be placed into a table, where the first column is the "Name of motif" and the secound is the "Element numbers". This would help to find what are the most frequent bindind sites under the peak regions.  Perhaps, sorting the list according to the element number would be useful as well.

**Comment by Raziel01** [comment] 2019-01-15 14:39
"Overlapping motfs" should be corrected to "Overlapping motifs"
I think replacing the panels would be better, like on the attached picture:
![experimenview](https://user-images.githubusercontent.com/19946687/51185413-54b9aa80-18d7-11e9-90b1-65d1f986f85d.png)
In this way, the field of experiment attributes can expanded to display all of the information.

**Comment by TravisCG** [comment] 2019-01-17 09:13
The request is implemented, but some times I can see NULL as motif name (for example here:
http://summit.med.unideb.hu/summitdb/experiment_view.php?exp=675)
I won't close this ticket until I find out what cause this.

**Comment by TravisCG** [comment] 2019-01-18 11:09
The problem caused by an error in the query. It is not fixed.

**Closed as completed by TravisCG** 2019-01-18 11:09 UTC
